
export interface User {
  id: number;
  name: string;
  email: string;
  companyName: string;
  website: string;
  city: string;
}
export const usersData: User[] = [
    {id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      companyName: 'Acme Corp',
      website: 'https://www.acmecorp.com',
      city: 'New York',
    },
    {id: 2,
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      companyName: 'Tech Innovators',
      website: 'https://www.techinnovators.com',
      city: 'San Francisco',
    },
    {id: 3,
      name: 'Michael Johnson',
      email: 'michael.johnson@example.com',
      companyName: 'Global Solutions',
      website: 'https://www.globalsolutions.com',
      city: 'London',
    },
    {id: 4,
      name: 'Emily Davis',
      email: 'emily.davis@example.com',
      companyName: 'Creative Enterprises',
      website: 'https://www.creativeenterprises.com',
      city: 'Berlin',
    },
    {id: 5,
      name: 'David Wilson',
      email: 'david.wilson@example.com',
      companyName: 'TechWorks',
      website: 'https://www.techworks.com',
      city: 'Austin',
    },
    {id: 6,
      name: 'Sarah Lee',
      email: 'sarah.lee@example.com',
      companyName: 'Digital Insights',
      website: 'https://www.digitalinsights.com',
      city: 'Chicago',
    },
    {id: 7,
      name: 'Daniel Kim',
      email: 'daniel.kim@example.com',
      companyName: 'Innovative Solutions',
      website: 'https://www.innovativesolutions.com',
      city: 'Seoul',
    },
    {id: 8,
      name: 'Olivia Brown',
      email: 'olivia.brown@example.com',
      companyName: 'Future Tech',
      website: 'https://www.futuretech.com',
      city: 'Toronto',
    },
    {id: 9,
      name: 'James Martinez',
      email: 'james.martinez@example.com',
      companyName: 'Tech Ventures',
      website: 'https://www.techventures.com',
      city: 'Barcelona',
    },
    {id: 10,
      name: 'Sophia Garcia',
      email: 'sophia.garcia@example.com',
      companyName: 'NextGen Technologies',
      website: 'https://www.nextgentech.com',
      city: 'Los Angeles',
    },
    {id: 11,
      name: 'Alexander White',
      email: 'alexander.white@example.com',
      companyName: 'Cloud Innovations',
      website: 'https://www.cloudinnovations.com',
      city: 'Paris',
    },
    {id: 12,
      name: 'Isabella Taylor',
      email: 'isabella.taylor@example.com',
      companyName: 'Design Studios',
      website: 'https://www.designstudios.com',
      city: 'Rome',
    },
    {id: 13,
      name: 'William Harris',
      email: 'william.harris@example.com',
      companyName: 'Advanced Systems',
      website: 'https://www.advancedsystems.com',
      city: 'Sydney',
    },
    {id: 14,
      name: 'Mia Clark',
      email: 'mia.clark@example.com',
      companyName: 'Smart Solutions',
      website: 'https://www.smartsolutions.com',
      city: 'Melbourne',
    },
    {id: 15,
      name: 'Benjamin Lewis',
      email: 'benjamin.lewis@example.com',
      companyName: 'NextEra Technologies',
      website: 'https://www.nexeratech.com',
      city: 'Madrid',
    },
  ];
  